import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { DashboardLayout } from '../components/dashboard-layout';

import { useMutation, useQuery, useQueryClient } from 'react-query';
import { getList } from './api/hello';

const Home = () => {
    // const query = useQuery('todo', () => [
    //     { id: 1, title: '11' },
    //     { id: 2, title: '22' },
    // ]);

    const { data, isLoading, isError, error } = useQuery('users', getList);

    const users = data?.data;

    console.log('data', data);
    console.log('users', users);

    if (isLoading) return <h1>Loding....</h1>;
    if (isError) return <h1>Error: {error}</h1>;

    return (
        <div>
            <ul>
                {data?.data.map((user) => (
                    <li key={user.id}>{user.email}</li>
                ))}
            </ul>
            <ul>
                {users.map((user) => (
                    <li key={user.id}>{user.email}</li>
                ))}
            </ul>
        </div>
    );
};

console.log('Home.getLayout', Home.getLayout);
Home.getLayout = (page) => <DashboardLayout>{page}</DashboardLayout>;

export default Home;

// export default function Home() {
//     return (
//         <div className={styles.container}>
//             <Head>
//                 <title>Create Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>

//             <main className={styles.main}>
//                 <h1 className={styles.title}>
//                     Welcome to <a href="https://nextjs.org">Next.js!</a>
//                 </h1>

//                 <p className={styles.description}>
//                     Get started by editing <code className={styles.code}>pages/index.js</code>
//                 </p>

//                 <div className={styles.grid}>
//                     <a href="https://nextjs.org/docs" className={styles.card}>
//                         <h2>Documentation &rarr;</h2>
//                         <p>Find in-depth information about Next.js features and API.</p>
//                     </a>

//                     <a href="https://nextjs.org/learn" className={styles.card}>
//                         <h2>Learn &rarr;</h2>
//                         <p>Learn about Next.js in an interactive course with quizzes!</p>
//                     </a>

//                     <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
//                         <h2>Examples &rarr;</h2>
//                         <p>Discover and deploy boilerplate example Next.js projects.</p>
//                     </a>

//                     <a
//                         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//                         className={styles.card}
//                     >
//                         <h2>Deploy &rarr;</h2>
//                         <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
//                     </a>
//                 </div>
//             </main>

//             <footer className={styles.footer}>
//                 <a
//                     href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//                     target="_blank"
//                     rel="noopener noreferrer"
//                 >
//                     Powered by{' '}
//                     <span className={styles.logo}>
//                         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//                     </span>
//                 </a>
//             </footer>
//         </div>
//     );
// }
